// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/runner/work/xlapjrt/xlapjrt/testing/testing.go:1:1
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package testing provide a cgx runtime for GX testing.
// The runtime includes GX test files statically linked in the binary.
package testing

import (
	"github.com/gx-org/xlapjrt/plugin"
	"github.com/gx-org/gx/api"
	"github.com/gx-org/gx/cgx/handle"
	gxtesting "github.com/gx-org/gx/tests/testing"
	pjrtstdlib "github.com/gx-org/xlapjrt/stdlib"
)

// #include <gx/golang/binder/cgx/cgx.h>
import _ "unsafe"

//export cgx_testing_runtime
func cgx_testing_runtime()  /*line :31:28*/_Ctype_struct_cgx_runtime_new_result /*line :31:59*/ {
	bld := gxtesting.NewBuilderStaticSource(pjrtstdlib.Stdlib)
	rtm, err := plugin.NewWithBuilder("cpu", bld)
	if err != nil {
		return  /*line :35:10*/_Ctype_struct_cgx_runtime_new_result /*line :35:41*/{
			error: ( /*line :36:12*/_Ctype_cgx_error /*line :36:23*/)(handle.Wrap[error](err)),
		}
	}
	return  /*line :39:9*/_Ctype_struct_cgx_runtime_new_result /*line :39:40*/{
		runtime:  /*line :40:12*/_Ctype_cgx_runtime /*line :40:25*/(handle.Wrap[*api.Runtime](rtm)),
	}
}
