# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run a release from a branch.

name: Build release

on:
  workflow_dispatch:

env:
  GOPJRT_NOSUDO: true
  GOPJRT_INSTALL_DIR: ${{ github.workspace }}/../gopjrtbin
  CGO_CFLAGS: -I${{ github.workspace }}/.. -I ${{ github.workspace }}/../gopjrtbin/include
  CGO_CPPFLAGS: -I${{ github.workspace }}/.. -I $${{ github.workspace }}/../gopjrtbin/include
  CGO_CXXFLAGS: -I${{ github.workspace }}/.. -I ${{ github.workspace }}/../gopjrtbin/include
  CGO_LDFLAGS: -labsl_status -labsl_statusor -L ${{ github.workspace }}/../gopjrtbin/lib -lgomlx_xlabuilder
  PJRT_PLUGIN_LIBRARY_PATH: ${{ github.workspace }}/../gopjrtbin/lib/gomlx/pjrt
  LD_LIBRARY_PATH: ${{ github.workspace }}/../gopjrtbin/lib 


jobs:
  BuildRelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Setup an identity
      run: git config user.email "noreply@github.com" && git config user.name "Github Action"

    - name: Install C++ dependencies
      run: sudo apt install -y libabsl-dev

    - name: Checkout GX to access cgx header files.
      run: |
        cd ..
        git clone https://github.com/gx-org/gx.git

    - name: Install gomlx
      run: |
        mkdir $GOPJRT_INSTALL_DIR
        curl -o $GOPJRT_INSTALL_DIR/install_linux_amd64.sh https://raw.githubusercontent.com/gomlx/gopjrt/main/cmd/install_linux_amd64.sh
        bash $GOPJRT_INSTALL_DIR/install_linux_amd64.sh 

    - name: Update all the dependencies to the latest release
      run: |
        export DEPS=$(go list -m -u all | grep "gx-org" | grep "\[v")
        [ "$DEPS" != "" ] && go list -m -u all | grep "gx-org" | grep "\[v" | awk '{print $1}' | xargs -n 1 go get -u
        go mod tidy

    - name: Run all the tests
      run: go test ./...

    - name: Commit changes if required
      run: git diff --quiet && git diff --staged --quiet || git commit -am 'Update dependencies.'

    - name: Checking status for debugging.
      run: git status

    - name: Push to origin
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Build a release tag
      run: |
        go run golang.org/x/exp/cmd/gorelease@latest
        export VERSION=$(go run golang.org/x/exp/cmd/gorelease@latest | grep Suggested | awk '{print $NF}')
        echo "VERSION: $VERSION"
        git tag $VERSION

    - name: Push tags
      run: git push --tags origin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
